<?php

/**
 * Implements hook_install().
 */
function unl_access_install() {
  // Rebuild node access permissions in batch mode.
  node_access_rebuild(TRUE);
}

/**
 * Implements hook_schema().
 */
function unl_access_schema() {
  $schema = array();
  $schema['unl_access_node_affiliation'] = array(
    'description' => 'UNL Affiliations allowed to access given nodes.',
    'fields' => array(
      'nid' => array(
        'type'     => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'affiliation' => array(
        'type'     => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'size'     => 'tiny',
      ),
    ),
    'primary key' => array('nid', 'affiliation'),
    'foreign keys' => array(
      'node' => array(
        'table'   => 'node',
        'columns' => array('nid' => 'nid'),
      ),
    )
  );

  return $schema;
}
